apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-api
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analytics-api
  template:
    metadata:
      labels:
        app: analytics-api
    spec:
      containers:
      - name: analytics-api
        image: saifudheenpv/globaltradesync-analytics:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-api-service
  namespace: default
spec:
  selector:
    app: analytics-api
  ports:
  - port: 80
    targetPort: 8000
  type: NodePort