apiVersion: apps/v1
kind: Deployment
metadata:
  name: globaltradesync-db
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: globaltradesync-db
  template:
    metadata:
      labels:
        app: globaltradesync-db
    spec:
      containers:
      - name: postgres
        image: postgres:13
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: shanu9090
        - name: POSTGRES_DB
          value: globaltradesync
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: globaltradesync-db-service
  namespace: default
  labels:
    app: globaltradesync-db
spec:
  selector:
    app: globaltradesync-db
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP